/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vut.gui;

import java.util.ArrayList;
import java.util.InputMismatchException;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
import vut.data.AmGamer;
import vut.data.Gamer;
import vut.data.ProGamer;

/**
 *
 * @author chauk
 */
public class GamersRegistrationApp extends javax.swing.JFrame {

    private ArrayList<Gamer> gamerArrList = new ArrayList<>();
    private static final int AMATEUR_REG_FEE = 250;
    private static final int PROFESSIONAL_REG_FEE = 500;
    private Gamer objGamer = null;

    /**
     * Creates new form GamersRegistrationApp
     */
    public GamersRegistrationApp() {
        initComponents();
        populateCmboCategory();
        populateCmboAge();
        populateCmboRank();
        grpRadButtons();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtID = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        cmboAge = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        txtRegisteredYrs = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        cmboRank = new javax.swing.JComboBox<>();
        cmboCategory = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        taGamer = new javax.swing.JTextArea();
        btnViewAll = new javax.swing.JButton();
        btnRegisterGamer = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        radAmateur = new javax.swing.JRadioButton();
        radprofessional = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 204, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("223232327_Gamers_RegistrationApp"));

        jLabel1.setText("Gamers ID-number:");

        jLabel2.setText("Gamer name:");

        jLabel3.setText("Gamer age:");

        jLabel4.setText("Registered years:");

        jLabel5.setText("Rank");

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Display Gamers"));

        taGamer.setColumns(20);
        taGamer.setRows(5);
        jScrollPane1.setViewportView(taGamer);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE)
                .addContainerGap())
        );

        btnViewAll.setBackground(new java.awt.Color(204, 204, 204));
        btnViewAll.setText("View All");
        btnViewAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewAllActionPerformed(evt);
            }
        });

        btnRegisterGamer.setBackground(new java.awt.Color(204, 204, 204));
        btnRegisterGamer.setText("Register Gamer");
        btnRegisterGamer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterGamerActionPerformed(evt);
            }
        });

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Gamer status"));

        radAmateur.setText("Amateur");
        radAmateur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radAmateurActionPerformed(evt);
            }
        });

        radprofessional.setText("Professional");
        radprofessional.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radprofessionalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(radprofessional, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(radAmateur, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(63, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(radAmateur)
                .addGap(18, 18, 18)
                .addComponent(radprofessional)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel7.setText("Category");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cmboCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmboRank, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(cmboAge, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtID)
                        .addComponent(txtName, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE)
                        .addComponent(txtRegisteredYrs)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 73, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnViewAll, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRegisterGamer, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(cmboAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(btnRegisterGamer, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtRegisteredYrs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmboRank, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnViewAll, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmboCategory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(58, 58, 58)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void radAmateurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radAmateurActionPerformed

        txtRegisteredYrs.setEnabled(false);
        cmboRank.setEnabled(false);

        cmboCategory.setEnabled(true);
    }//GEN-LAST:event_radAmateurActionPerformed

    private void radprofessionalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radprofessionalActionPerformed
        cmboCategory.setEnabled(false);

        txtRegisteredYrs.setEnabled(true);
        cmboRank.setEnabled(true);
    }//GEN-LAST:event_radprofessionalActionPerformed

    private void btnRegisterGamerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterGamerActionPerformed

        if (!txtID.getText().isEmpty() && !txtName.getText().isEmpty()) {

            try {

                if (radAmateur.isSelected()) {
                    objGamer = new AmGamer(txtID.getText(), txtName.getText(),
                            Integer.parseInt(cmboAge.getSelectedItem().toString()),
                            Integer.parseInt(cmboCategory.getSelectedItem().toString()));
                    gamerArrList.add(objGamer);

                    taGamer.setText("Code\t" + "ID number\t" + "Name\t\t"
                            + "Category\t" + "Registration fee\t" + "Discount\n");
                    taGamer.append(objGamer.toString() + '\t' + "R"+(AMATEUR_REG_FEE - objGamer.calculateDiscount(AMATEUR_REG_FEE))
                            + '\t' + "R"+objGamer.calculateDiscount(AMATEUR_REG_FEE) + "\n");
                    clear();
                } else if (radprofessional.isSelected()) {
                    objGamer = new ProGamer(txtID.getText(), txtName.getText(),
                            Integer.parseInt(cmboAge.getSelectedItem().toString()),
                            Integer.parseInt(txtRegisteredYrs.getText()),
                            Integer.parseInt(cmboRank.getSelectedItem().toString()));
                    gamerArrList.add(objGamer);

                    taGamer.setText("Code\t" + "ID number\t" + "Name\t\t"
                            + "Years\t" + "Rank\t" + "Registration fee\t" + "Discount\n");
                    taGamer.append(objGamer.toString() + '\t'
                            + "R"+(PROFESSIONAL_REG_FEE - objGamer.calculateDiscount(PROFESSIONAL_REG_FEE))
                            + '\t' +"R"+ objGamer.calculateDiscount(PROFESSIONAL_REG_FEE) + "\n");
                    clear();
                }

            } catch (InputMismatchException ex) {

                JOptionPane.showMessageDialog(null, "", "Input Invalid", JOptionPane.ERROR_MESSAGE);
            }

        } else {
            JOptionPane.showMessageDialog(null, "Name and/or ID Text Field are Empty", "Input Invalid", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_btnRegisterGamerActionPerformed

    private void btnViewAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewAllActionPerformed

        taGamer.setText("");

        // Display Professional Gamers
        taGamer.append("Professional gamers\n " + "Code\t" + "ID number\t" + "Name\t\t"
                + "Years\t" + "Rank\t" + "Registration fee\t" + "Discount\n");
        for (int i = 0; i < gamerArrList.size(); i++) {
            if (gamerArrList.get(i).getCode().charAt(0) == 'P') {
                taGamer.append(gamerArrList.get(i).toString() + '\t'
                        +"R"+ (PROFESSIONAL_REG_FEE - objGamer.calculateDiscount(PROFESSIONAL_REG_FEE))
                        + '\t' +"R"+ objGamer.calculateDiscount(PROFESSIONAL_REG_FEE) + "\n");
            }
        }

        // Display Amateur Gamers
        taGamer.append("\nAmateur gamers\n" + "Code\t" + "ID number\t" + "Name\t\t"
                + "Category\t" + "Registration fee\t" + "Discount\n");
        for (int i = 0; i < gamerArrList.size(); i++) {
            if (gamerArrList.get(i).getCode().charAt(0) == 'A') {
                taGamer.append(gamerArrList.get(i).toString() + '\t'
                        +"R"+ (AMATEUR_REG_FEE - objGamer.calculateDiscount(AMATEUR_REG_FEE))
                        + '\t' + "R"+objGamer.calculateDiscount(AMATEUR_REG_FEE) + "\n");
            }
        }

    }//GEN-LAST:event_btnViewAllActionPerformed

    public void populateCmboCategory() {

        String strCategory;
        for (int i = 1; i <= 3; i++) {
            strCategory = Integer.toString(i);
            cmboCategory.addItem(strCategory);
        }
    }

    private void populateCmboAge() {

        String strAge;
        for (int i = 10; i <= 80; i++) {
            strAge = Integer.toString(i);
            cmboAge.addItem(strAge);
        }
    }

    private void populateCmboRank() {

        String strRank;
        for (int i = 0; i <= 99; i++) {
            strRank = Integer.toString(i);
            cmboRank.addItem(strRank);
        }
    }

    private void grpRadButtons() {

        ButtonGroup grpRad = new ButtonGroup();

        grpRad.add(radAmateur);
        grpRad.add(radprofessional);
    }

    private void clear() {
        txtID.setText("");
        txtName.setText("");
        txtRegisteredYrs.setText("");
        cmboAge.setSelectedIndex(-1);
        cmboCategory.setSelectedIndex(-1);
        cmboRank.setSelectedIndex(-1);

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GamersRegistrationApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GamersRegistrationApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GamersRegistrationApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GamersRegistrationApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GamersRegistrationApp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegisterGamer;
    private javax.swing.JButton btnViewAll;
    private javax.swing.JComboBox<String> cmboAge;
    private javax.swing.JComboBox<String> cmboCategory;
    private javax.swing.JComboBox<String> cmboRank;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton radAmateur;
    private javax.swing.JRadioButton radprofessional;
    private javax.swing.JTextArea taGamer;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtRegisteredYrs;
    // End of variables declaration//GEN-END:variables
}
